-- Comments in SQL Start with dash-dash --
-- 1. products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('chair', 44, 'false');
-- 2. products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('stool',25.99 , 'true');  
-- 3. products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('table', 124, 'false');    
-- 4. products_db=# SELECT * FROM products;                                                                                                   ;
--  id | name  | price | can_be_returned 
-- ----+-------+-------+-----------------
--   1 | chair |    44 | f
--   2 | stool | 25.99 | t
--   3 | table |   124 | f
-- (3 rows)
-- 5. products_db=# SELECT name FROM products;
-- 6. products_db=# SELECT name, price FROM products;
-- 7. products_db=# INSERT INTO products (name, price, can_be_returned) VALUES ('lamp', 20, 'true');
-- 8. products_db=# SELECT name FROM products WHERE can_be_returned = 'true';
-- 9. products_db=# SELECT name FROM products WHERE price < 44;
-- 10. products_db=# SELECT name FROM products WHERE price BETWEEN 22.50 AND 99.99;
-- 11. products_db=# UPDATE products SET price = price -19; 
-- -- decreased by 19 due to lamp price of 20 constriant
-- 12. products_db=# DELETE FROM products WHERE price < 25;
-- 13. products_db=# UPDATE products SET price = price +20;
-- 14. products_db=# UPDATE products SET can_be_returned = 'true';
